version: 0.0
os: linux
files:
  - source: ./galaxychatbots-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/jar
hooks:
  BeforeInstall:
    - location: ./check.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./stop.sh
      timeout: 300
      runas: root
