version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      # - cd ./GalaxyChatbot
      - echo build started at `date`
      - openssl enc -d -aes-256-ecb -md md5 -in src/main/resources/application.properties.secrets -out src/main/resources/application.properties -k $SECRETS_KEY
      - echo decrepted at `date`
      - mvn clean install

artifacts:
  files:
    - 'target/galaxy-chatbot-1.0.0.jar'
    - 'appspec.yml'
    - 'deploy/check.sh'
    - 'deploy/install.sh'
    - 'deploy/start.sh'
    - 'deploy/stop.sh'
  discard-paths: yes

